/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.asset.list.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the AssetListEntryLocalization service. Represents a row in the &quot;AssetListEntryLocalization&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.asset.list.model.impl.AssetListEntryLocalizationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.asset.list.model.impl.AssetListEntryLocalizationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AssetListEntryLocalization
 * @see com.liferay.asset.list.model.impl.AssetListEntryLocalizationImpl
 * @see com.liferay.asset.list.model.impl.AssetListEntryLocalizationModelImpl
 * @generated
 */
@ProviderType
public interface AssetListEntryLocalizationModel extends BaseModel<AssetListEntryLocalization>,
	MVCCModel, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a asset list entry localization model instance should use the {@link AssetListEntryLocalization} interface instead.
	 */

	/**
	 * Returns the primary key of this asset list entry localization.
	 *
	 * @return the primary key of this asset list entry localization
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this asset list entry localization.
	 *
	 * @param primaryKey the primary key of this asset list entry localization
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this asset list entry localization.
	 *
	 * @return the mvcc version of this asset list entry localization
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this asset list entry localization.
	 *
	 * @param mvccVersion the mvcc version of this asset list entry localization
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the asset list entry localization ID of this asset list entry localization.
	 *
	 * @return the asset list entry localization ID of this asset list entry localization
	 */
	public long getAssetListEntryLocalizationId();

	/**
	 * Sets the asset list entry localization ID of this asset list entry localization.
	 *
	 * @param assetListEntryLocalizationId the asset list entry localization ID of this asset list entry localization
	 */
	public void setAssetListEntryLocalizationId(
		long assetListEntryLocalizationId);

	/**
	 * Returns the company ID of this asset list entry localization.
	 *
	 * @return the company ID of this asset list entry localization
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this asset list entry localization.
	 *
	 * @param companyId the company ID of this asset list entry localization
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the asset list entry ID of this asset list entry localization.
	 *
	 * @return the asset list entry ID of this asset list entry localization
	 */
	public long getAssetListEntryId();

	/**
	 * Sets the asset list entry ID of this asset list entry localization.
	 *
	 * @param assetListEntryId the asset list entry ID of this asset list entry localization
	 */
	public void setAssetListEntryId(long assetListEntryId);

	/**
	 * Returns the language ID of this asset list entry localization.
	 *
	 * @return the language ID of this asset list entry localization
	 */
	@AutoEscape
	public String getLanguageId();

	/**
	 * Sets the language ID of this asset list entry localization.
	 *
	 * @param languageId the language ID of this asset list entry localization
	 */
	public void setLanguageId(String languageId);

	/**
	 * Returns the title of this asset list entry localization.
	 *
	 * @return the title of this asset list entry localization
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this asset list entry localization.
	 *
	 * @param title the title of this asset list entry localization
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this asset list entry localization.
	 *
	 * @return the description of this asset list entry localization
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this asset list entry localization.
	 *
	 * @param description the description of this asset list entry localization
	 */
	public void setDescription(String description);

	/**
	 * Returns the group ID of this asset list entry localization.
	 *
	 * @return the group ID of this asset list entry localization
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this asset list entry localization.
	 *
	 * @param groupId the group ID of this asset list entry localization
	 */
	public void setGroupId(long groupId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(AssetListEntryLocalization assetListEntryLocalization);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AssetListEntryLocalization> toCacheModel();

	@Override
	public AssetListEntryLocalization toEscapedModel();

	@Override
	public AssetListEntryLocalization toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}