/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.layout.page.template.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.layout.page.template.model.LayoutPageTemplateVersion;
import com.liferay.layout.page.template.model.LayoutPageTemplateVersionModel;
import com.liferay.layout.page.template.model.LayoutPageTemplateVersionSoap;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the LayoutPageTemplateVersion service. Represents a row in the &quot;LayoutPageTemplateVersion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>LayoutPageTemplateVersionModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LayoutPageTemplateVersionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LayoutPageTemplateVersionImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class LayoutPageTemplateVersionModelImpl
	extends BaseModelImpl<LayoutPageTemplateVersion>
	implements LayoutPageTemplateVersionModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a layout page template version model instance should use the <code>LayoutPageTemplateVersion</code> interface instead.
	 */
	public static final String TABLE_NAME = "LayoutPageTemplateVersion";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"layoutPageTemplateVersionId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"layoutPageTemplateEntryId", Types.BIGINT}, {"plid", Types.BIGINT},
		{"version", Types.DOUBLE}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("layoutPageTemplateVersionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("layoutPageTemplateEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("plid", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("version", Types.DOUBLE);
	}

	public static final String TABLE_SQL_CREATE =
		"create table LayoutPageTemplateVersion (uuid_ VARCHAR(75) null,layoutPageTemplateVersionId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,layoutPageTemplateEntryId LONG,plid LONG,version DOUBLE)";

	public static final String TABLE_SQL_DROP =
		"drop table LayoutPageTemplateVersion";

	public static final String ORDER_BY_JPQL =
		" ORDER BY layoutPageTemplateVersion.layoutPageTemplateVersionId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY LayoutPageTemplateVersion.layoutPageTemplateVersionId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.layout.page.template.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.com.liferay.layout.page.template.model.LayoutPageTemplateVersion"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		com.liferay.layout.page.template.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.com.liferay.layout.page.template.model.LayoutPageTemplateVersion"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		com.liferay.layout.page.template.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.com.liferay.layout.page.template.model.LayoutPageTemplateVersion"),
		true);

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long LAYOUTPAGETEMPLATEENTRYID_COLUMN_BITMASK = 4L;

	public static final long UUID_COLUMN_BITMASK = 8L;

	public static final long LAYOUTPAGETEMPLATEVERSIONID_COLUMN_BITMASK = 16L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static LayoutPageTemplateVersion toModel(
		LayoutPageTemplateVersionSoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		LayoutPageTemplateVersion model = new LayoutPageTemplateVersionImpl();

		model.setUuid(soapModel.getUuid());
		model.setLayoutPageTemplateVersionId(
			soapModel.getLayoutPageTemplateVersionId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setLayoutPageTemplateEntryId(
			soapModel.getLayoutPageTemplateEntryId());
		model.setPlid(soapModel.getPlid());
		model.setVersion(soapModel.getVersion());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<LayoutPageTemplateVersion> toModels(
		LayoutPageTemplateVersionSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<LayoutPageTemplateVersion> models =
			new ArrayList<LayoutPageTemplateVersion>(soapModels.length);

		for (LayoutPageTemplateVersionSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.layout.page.template.service.util.ServiceProps.get(
			"lock.expiration.time.com.liferay.layout.page.template.model.LayoutPageTemplateVersion"));

	public LayoutPageTemplateVersionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _layoutPageTemplateVersionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLayoutPageTemplateVersionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _layoutPageTemplateVersionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LayoutPageTemplateVersion.class;
	}

	@Override
	public String getModelClassName() {
		return LayoutPageTemplateVersion.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<LayoutPageTemplateVersion, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<LayoutPageTemplateVersion, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LayoutPageTemplateVersion, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((LayoutPageTemplateVersion)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<LayoutPageTemplateVersion, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<LayoutPageTemplateVersion, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(LayoutPageTemplateVersion)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<LayoutPageTemplateVersion, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<LayoutPageTemplateVersion, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map
		<String, Function<LayoutPageTemplateVersion, Object>>
			_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<LayoutPageTemplateVersion, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<LayoutPageTemplateVersion, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<LayoutPageTemplateVersion, Object>>();
		Map<String, BiConsumer<LayoutPageTemplateVersion, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<LayoutPageTemplateVersion, ?>>();

		attributeGetterFunctions.put(
			"uuid", LayoutPageTemplateVersion::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<LayoutPageTemplateVersion, String>)
				LayoutPageTemplateVersion::setUuid);
		attributeGetterFunctions.put(
			"layoutPageTemplateVersionId",
			LayoutPageTemplateVersion::getLayoutPageTemplateVersionId);
		attributeSetterBiConsumers.put(
			"layoutPageTemplateVersionId",
			(BiConsumer<LayoutPageTemplateVersion, Long>)
				LayoutPageTemplateVersion::setLayoutPageTemplateVersionId);
		attributeGetterFunctions.put(
			"groupId", LayoutPageTemplateVersion::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<LayoutPageTemplateVersion, Long>)
				LayoutPageTemplateVersion::setGroupId);
		attributeGetterFunctions.put(
			"companyId", LayoutPageTemplateVersion::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<LayoutPageTemplateVersion, Long>)
				LayoutPageTemplateVersion::setCompanyId);
		attributeGetterFunctions.put(
			"userId", LayoutPageTemplateVersion::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<LayoutPageTemplateVersion, Long>)
				LayoutPageTemplateVersion::setUserId);
		attributeGetterFunctions.put(
			"userName", LayoutPageTemplateVersion::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<LayoutPageTemplateVersion, String>)
				LayoutPageTemplateVersion::setUserName);
		attributeGetterFunctions.put(
			"createDate", LayoutPageTemplateVersion::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<LayoutPageTemplateVersion, Date>)
				LayoutPageTemplateVersion::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", LayoutPageTemplateVersion::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<LayoutPageTemplateVersion, Date>)
				LayoutPageTemplateVersion::setModifiedDate);
		attributeGetterFunctions.put(
			"layoutPageTemplateEntryId",
			LayoutPageTemplateVersion::getLayoutPageTemplateEntryId);
		attributeSetterBiConsumers.put(
			"layoutPageTemplateEntryId",
			(BiConsumer<LayoutPageTemplateVersion, Long>)
				LayoutPageTemplateVersion::setLayoutPageTemplateEntryId);
		attributeGetterFunctions.put(
			"plid", LayoutPageTemplateVersion::getPlid);
		attributeSetterBiConsumers.put(
			"plid",
			(BiConsumer<LayoutPageTemplateVersion, Long>)
				LayoutPageTemplateVersion::setPlid);
		attributeGetterFunctions.put(
			"version", LayoutPageTemplateVersion::getVersion);
		attributeSetterBiConsumers.put(
			"version",
			(BiConsumer<LayoutPageTemplateVersion, Double>)
				LayoutPageTemplateVersion::setVersion);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getLayoutPageTemplateVersionId() {
		return _layoutPageTemplateVersionId;
	}

	@Override
	public void setLayoutPageTemplateVersionId(
		long layoutPageTemplateVersionId) {

		_layoutPageTemplateVersionId = layoutPageTemplateVersionId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getLayoutPageTemplateEntryId() {
		return _layoutPageTemplateEntryId;
	}

	@Override
	public void setLayoutPageTemplateEntryId(long layoutPageTemplateEntryId) {
		_columnBitmask |= LAYOUTPAGETEMPLATEENTRYID_COLUMN_BITMASK;

		if (!_setOriginalLayoutPageTemplateEntryId) {
			_setOriginalLayoutPageTemplateEntryId = true;

			_originalLayoutPageTemplateEntryId = _layoutPageTemplateEntryId;
		}

		_layoutPageTemplateEntryId = layoutPageTemplateEntryId;
	}

	public long getOriginalLayoutPageTemplateEntryId() {
		return _originalLayoutPageTemplateEntryId;
	}

	@JSON
	@Override
	public long getPlid() {
		return _plid;
	}

	@Override
	public void setPlid(long plid) {
		_plid = plid;
	}

	@JSON
	@Override
	public double getVersion() {
		return _version;
	}

	@Override
	public void setVersion(double version) {
		_version = version;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(
				LayoutPageTemplateVersion.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), LayoutPageTemplateVersion.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LayoutPageTemplateVersion toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel =
				(LayoutPageTemplateVersion)ProxyUtil.newProxyInstance(
					_classLoader, _escapedModelInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LayoutPageTemplateVersionImpl layoutPageTemplateVersionImpl =
			new LayoutPageTemplateVersionImpl();

		layoutPageTemplateVersionImpl.setUuid(getUuid());
		layoutPageTemplateVersionImpl.setLayoutPageTemplateVersionId(
			getLayoutPageTemplateVersionId());
		layoutPageTemplateVersionImpl.setGroupId(getGroupId());
		layoutPageTemplateVersionImpl.setCompanyId(getCompanyId());
		layoutPageTemplateVersionImpl.setUserId(getUserId());
		layoutPageTemplateVersionImpl.setUserName(getUserName());
		layoutPageTemplateVersionImpl.setCreateDate(getCreateDate());
		layoutPageTemplateVersionImpl.setModifiedDate(getModifiedDate());
		layoutPageTemplateVersionImpl.setLayoutPageTemplateEntryId(
			getLayoutPageTemplateEntryId());
		layoutPageTemplateVersionImpl.setPlid(getPlid());
		layoutPageTemplateVersionImpl.setVersion(getVersion());

		layoutPageTemplateVersionImpl.resetOriginalValues();

		return layoutPageTemplateVersionImpl;
	}

	@Override
	public int compareTo(LayoutPageTemplateVersion layoutPageTemplateVersion) {
		long primaryKey = layoutPageTemplateVersion.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof LayoutPageTemplateVersion)) {
			return false;
		}

		LayoutPageTemplateVersion layoutPageTemplateVersion =
			(LayoutPageTemplateVersion)obj;

		long primaryKey = layoutPageTemplateVersion.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		LayoutPageTemplateVersionModelImpl layoutPageTemplateVersionModelImpl =
			this;

		layoutPageTemplateVersionModelImpl._originalUuid =
			layoutPageTemplateVersionModelImpl._uuid;

		layoutPageTemplateVersionModelImpl._originalGroupId =
			layoutPageTemplateVersionModelImpl._groupId;

		layoutPageTemplateVersionModelImpl._setOriginalGroupId = false;

		layoutPageTemplateVersionModelImpl._originalCompanyId =
			layoutPageTemplateVersionModelImpl._companyId;

		layoutPageTemplateVersionModelImpl._setOriginalCompanyId = false;

		layoutPageTemplateVersionModelImpl._setModifiedDate = false;

		layoutPageTemplateVersionModelImpl._originalLayoutPageTemplateEntryId =
			layoutPageTemplateVersionModelImpl._layoutPageTemplateEntryId;

		layoutPageTemplateVersionModelImpl.
			_setOriginalLayoutPageTemplateEntryId = false;

		layoutPageTemplateVersionModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<LayoutPageTemplateVersion> toCacheModel() {
		LayoutPageTemplateVersionCacheModel
			layoutPageTemplateVersionCacheModel =
				new LayoutPageTemplateVersionCacheModel();

		layoutPageTemplateVersionCacheModel.uuid = getUuid();

		String uuid = layoutPageTemplateVersionCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			layoutPageTemplateVersionCacheModel.uuid = null;
		}

		layoutPageTemplateVersionCacheModel.layoutPageTemplateVersionId =
			getLayoutPageTemplateVersionId();

		layoutPageTemplateVersionCacheModel.groupId = getGroupId();

		layoutPageTemplateVersionCacheModel.companyId = getCompanyId();

		layoutPageTemplateVersionCacheModel.userId = getUserId();

		layoutPageTemplateVersionCacheModel.userName = getUserName();

		String userName = layoutPageTemplateVersionCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			layoutPageTemplateVersionCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			layoutPageTemplateVersionCacheModel.createDate =
				createDate.getTime();
		}
		else {
			layoutPageTemplateVersionCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			layoutPageTemplateVersionCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			layoutPageTemplateVersionCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		layoutPageTemplateVersionCacheModel.layoutPageTemplateEntryId =
			getLayoutPageTemplateEntryId();

		layoutPageTemplateVersionCacheModel.plid = getPlid();

		layoutPageTemplateVersionCacheModel.version = getVersion();

		return layoutPageTemplateVersionCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<LayoutPageTemplateVersion, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<LayoutPageTemplateVersion, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LayoutPageTemplateVersion, Object>
				attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(
				attributeGetterFunction.apply((LayoutPageTemplateVersion)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<LayoutPageTemplateVersion, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<LayoutPageTemplateVersion, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LayoutPageTemplateVersion, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((LayoutPageTemplateVersion)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader =
		LayoutPageTemplateVersion.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
		LayoutPageTemplateVersion.class, ModelWrapper.class
	};

	private String _uuid;
	private String _originalUuid;
	private long _layoutPageTemplateVersionId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _layoutPageTemplateEntryId;
	private long _originalLayoutPageTemplateEntryId;
	private boolean _setOriginalLayoutPageTemplateEntryId;
	private long _plid;
	private double _version;
	private long _columnBitmask;
	private LayoutPageTemplateVersion _escapedModel;

}