/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.layout.page.template.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

/**
 * The base model interface for the LayoutPageTemplateVersion service. Represents a row in the &quot;LayoutPageTemplateVersion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.layout.page.template.model.impl.LayoutPageTemplateVersionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.layout.page.template.model.impl.LayoutPageTemplateVersionImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LayoutPageTemplateVersion
 * @generated
 */
@ProviderType
public interface LayoutPageTemplateVersionModel
	extends BaseModel<LayoutPageTemplateVersion>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a layout page template version model instance should use the {@link LayoutPageTemplateVersion} interface instead.
	 */

	/**
	 * Returns the primary key of this layout page template version.
	 *
	 * @return the primary key of this layout page template version
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this layout page template version.
	 *
	 * @param primaryKey the primary key of this layout page template version
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this layout page template version.
	 *
	 * @return the uuid of this layout page template version
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this layout page template version.
	 *
	 * @param uuid the uuid of this layout page template version
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the layout page template version ID of this layout page template version.
	 *
	 * @return the layout page template version ID of this layout page template version
	 */
	public long getLayoutPageTemplateVersionId();

	/**
	 * Sets the layout page template version ID of this layout page template version.
	 *
	 * @param layoutPageTemplateVersionId the layout page template version ID of this layout page template version
	 */
	public void setLayoutPageTemplateVersionId(
		long layoutPageTemplateVersionId);

	/**
	 * Returns the group ID of this layout page template version.
	 *
	 * @return the group ID of this layout page template version
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this layout page template version.
	 *
	 * @param groupId the group ID of this layout page template version
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this layout page template version.
	 *
	 * @return the company ID of this layout page template version
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this layout page template version.
	 *
	 * @param companyId the company ID of this layout page template version
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this layout page template version.
	 *
	 * @return the user ID of this layout page template version
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this layout page template version.
	 *
	 * @param userId the user ID of this layout page template version
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this layout page template version.
	 *
	 * @return the user uuid of this layout page template version
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this layout page template version.
	 *
	 * @param userUuid the user uuid of this layout page template version
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this layout page template version.
	 *
	 * @return the user name of this layout page template version
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this layout page template version.
	 *
	 * @param userName the user name of this layout page template version
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this layout page template version.
	 *
	 * @return the create date of this layout page template version
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this layout page template version.
	 *
	 * @param createDate the create date of this layout page template version
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this layout page template version.
	 *
	 * @return the modified date of this layout page template version
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this layout page template version.
	 *
	 * @param modifiedDate the modified date of this layout page template version
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the layout page template entry ID of this layout page template version.
	 *
	 * @return the layout page template entry ID of this layout page template version
	 */
	public long getLayoutPageTemplateEntryId();

	/**
	 * Sets the layout page template entry ID of this layout page template version.
	 *
	 * @param layoutPageTemplateEntryId the layout page template entry ID of this layout page template version
	 */
	public void setLayoutPageTemplateEntryId(long layoutPageTemplateEntryId);

	/**
	 * Returns the plid of this layout page template version.
	 *
	 * @return the plid of this layout page template version
	 */
	public long getPlid();

	/**
	 * Sets the plid of this layout page template version.
	 *
	 * @param plid the plid of this layout page template version
	 */
	public void setPlid(long plid);

	/**
	 * Returns the version of this layout page template version.
	 *
	 * @return the version of this layout page template version
	 */
	public double getVersion();

	/**
	 * Sets the version of this layout page template version.
	 *
	 * @param version the version of this layout page template version
	 */
	public void setVersion(double version);

}