/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.asset.lists.service.base;

import com.liferay.asset.lists.model.AssetList;
import com.liferay.asset.lists.service.AssetListService;
import com.liferay.asset.lists.service.persistence.AssetListPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the asset list remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.asset.lists.service.impl.AssetListServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.asset.lists.service.impl.AssetListServiceImpl
 * @see com.liferay.asset.lists.service.AssetListServiceUtil
 * @generated
 */
public abstract class AssetListServiceBaseImpl extends BaseServiceImpl
	implements AssetListService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.asset.lists.service.AssetListServiceUtil} to access the asset list remote service.
	 */

	/**
	 * Returns the asset list local service.
	 *
	 * @return the asset list local service
	 */
	public com.liferay.asset.lists.service.AssetListLocalService getAssetListLocalService() {
		return assetListLocalService;
	}

	/**
	 * Sets the asset list local service.
	 *
	 * @param assetListLocalService the asset list local service
	 */
	public void setAssetListLocalService(
		com.liferay.asset.lists.service.AssetListLocalService assetListLocalService) {
		this.assetListLocalService = assetListLocalService;
	}

	/**
	 * Returns the asset list remote service.
	 *
	 * @return the asset list remote service
	 */
	public AssetListService getAssetListService() {
		return assetListService;
	}

	/**
	 * Sets the asset list remote service.
	 *
	 * @param assetListService the asset list remote service
	 */
	public void setAssetListService(AssetListService assetListService) {
		this.assetListService = assetListService;
	}

	/**
	 * Returns the asset list persistence.
	 *
	 * @return the asset list persistence
	 */
	public AssetListPersistence getAssetListPersistence() {
		return assetListPersistence;
	}

	/**
	 * Sets the asset list persistence.
	 *
	 * @param assetListPersistence the asset list persistence
	 */
	public void setAssetListPersistence(
		AssetListPersistence assetListPersistence) {
		this.assetListPersistence = assetListPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AssetListService.class.getName();
	}

	protected Class<?> getModelClass() {
		return AssetList.class;
	}

	protected String getModelClassName() {
		return AssetList.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = assetListPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.liferay.asset.lists.service.AssetListLocalService.class)
	protected com.liferay.asset.lists.service.AssetListLocalService assetListLocalService;
	@BeanReference(type = AssetListService.class)
	protected AssetListService assetListService;
	@BeanReference(type = AssetListPersistence.class)
	protected AssetListPersistence assetListPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
}