/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.asset.list.service.base;

import com.liferay.asset.list.model.AssetListEntryAssetEntryRel;
import com.liferay.asset.list.service.AssetListEntryAssetEntryRelService;
import com.liferay.asset.list.service.persistence.AssetListEntryAssetEntryRelPersistence;
import com.liferay.asset.list.service.persistence.AssetListEntryPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the asset list entry asset entry rel remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.asset.list.service.impl.AssetListEntryAssetEntryRelServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.asset.list.service.impl.AssetListEntryAssetEntryRelServiceImpl
 * @see com.liferay.asset.list.service.AssetListEntryAssetEntryRelServiceUtil
 * @generated
 */
public abstract class AssetListEntryAssetEntryRelServiceBaseImpl
	extends BaseServiceImpl implements AssetListEntryAssetEntryRelService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.asset.list.service.AssetListEntryAssetEntryRelServiceUtil} to access the asset list entry asset entry rel remote service.
	 */

	/**
	 * Returns the asset list entry asset entry rel local service.
	 *
	 * @return the asset list entry asset entry rel local service
	 */
	public com.liferay.asset.list.service.AssetListEntryAssetEntryRelLocalService getAssetListEntryAssetEntryRelLocalService() {
		return assetListEntryAssetEntryRelLocalService;
	}

	/**
	 * Sets the asset list entry asset entry rel local service.
	 *
	 * @param assetListEntryAssetEntryRelLocalService the asset list entry asset entry rel local service
	 */
	public void setAssetListEntryAssetEntryRelLocalService(
		com.liferay.asset.list.service.AssetListEntryAssetEntryRelLocalService assetListEntryAssetEntryRelLocalService) {
		this.assetListEntryAssetEntryRelLocalService = assetListEntryAssetEntryRelLocalService;
	}

	/**
	 * Returns the asset list entry asset entry rel remote service.
	 *
	 * @return the asset list entry asset entry rel remote service
	 */
	public AssetListEntryAssetEntryRelService getAssetListEntryAssetEntryRelService() {
		return assetListEntryAssetEntryRelService;
	}

	/**
	 * Sets the asset list entry asset entry rel remote service.
	 *
	 * @param assetListEntryAssetEntryRelService the asset list entry asset entry rel remote service
	 */
	public void setAssetListEntryAssetEntryRelService(
		AssetListEntryAssetEntryRelService assetListEntryAssetEntryRelService) {
		this.assetListEntryAssetEntryRelService = assetListEntryAssetEntryRelService;
	}

	/**
	 * Returns the asset list entry asset entry rel persistence.
	 *
	 * @return the asset list entry asset entry rel persistence
	 */
	public AssetListEntryAssetEntryRelPersistence getAssetListEntryAssetEntryRelPersistence() {
		return assetListEntryAssetEntryRelPersistence;
	}

	/**
	 * Sets the asset list entry asset entry rel persistence.
	 *
	 * @param assetListEntryAssetEntryRelPersistence the asset list entry asset entry rel persistence
	 */
	public void setAssetListEntryAssetEntryRelPersistence(
		AssetListEntryAssetEntryRelPersistence assetListEntryAssetEntryRelPersistence) {
		this.assetListEntryAssetEntryRelPersistence = assetListEntryAssetEntryRelPersistence;
	}

	/**
	 * Returns the asset list entry local service.
	 *
	 * @return the asset list entry local service
	 */
	public com.liferay.asset.list.service.AssetListEntryLocalService getAssetListEntryLocalService() {
		return assetListEntryLocalService;
	}

	/**
	 * Sets the asset list entry local service.
	 *
	 * @param assetListEntryLocalService the asset list entry local service
	 */
	public void setAssetListEntryLocalService(
		com.liferay.asset.list.service.AssetListEntryLocalService assetListEntryLocalService) {
		this.assetListEntryLocalService = assetListEntryLocalService;
	}

	/**
	 * Returns the asset list entry remote service.
	 *
	 * @return the asset list entry remote service
	 */
	public com.liferay.asset.list.service.AssetListEntryService getAssetListEntryService() {
		return assetListEntryService;
	}

	/**
	 * Sets the asset list entry remote service.
	 *
	 * @param assetListEntryService the asset list entry remote service
	 */
	public void setAssetListEntryService(
		com.liferay.asset.list.service.AssetListEntryService assetListEntryService) {
		this.assetListEntryService = assetListEntryService;
	}

	/**
	 * Returns the asset list entry persistence.
	 *
	 * @return the asset list entry persistence
	 */
	public AssetListEntryPersistence getAssetListEntryPersistence() {
		return assetListEntryPersistence;
	}

	/**
	 * Sets the asset list entry persistence.
	 *
	 * @param assetListEntryPersistence the asset list entry persistence
	 */
	public void setAssetListEntryPersistence(
		AssetListEntryPersistence assetListEntryPersistence) {
		this.assetListEntryPersistence = assetListEntryPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AssetListEntryAssetEntryRelService.class.getName();
	}

	protected Class<?> getModelClass() {
		return AssetListEntryAssetEntryRel.class;
	}

	protected String getModelClassName() {
		return AssetListEntryAssetEntryRel.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = assetListEntryAssetEntryRelPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.liferay.asset.list.service.AssetListEntryAssetEntryRelLocalService.class)
	protected com.liferay.asset.list.service.AssetListEntryAssetEntryRelLocalService assetListEntryAssetEntryRelLocalService;
	@BeanReference(type = AssetListEntryAssetEntryRelService.class)
	protected AssetListEntryAssetEntryRelService assetListEntryAssetEntryRelService;
	@BeanReference(type = AssetListEntryAssetEntryRelPersistence.class)
	protected AssetListEntryAssetEntryRelPersistence assetListEntryAssetEntryRelPersistence;
	@BeanReference(type = com.liferay.asset.list.service.AssetListEntryLocalService.class)
	protected com.liferay.asset.list.service.AssetListEntryLocalService assetListEntryLocalService;
	@BeanReference(type = com.liferay.asset.list.service.AssetListEntryService.class)
	protected com.liferay.asset.list.service.AssetListEntryService assetListEntryService;
	@BeanReference(type = AssetListEntryPersistence.class)
	protected AssetListEntryPersistence assetListEntryPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
}