/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.friendly.url.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.friendly.url.model.FriendlyURLLocalization;
import com.liferay.friendly.url.service.FriendlyURLLocalizationLocalService;
import com.liferay.friendly.url.service.persistence.FriendlyURLLocalizationPersistence;
import com.liferay.friendly.url.service.persistence.FriendlyURLPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the friendly url localization local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.friendly.url.service.impl.FriendlyURLLocalizationLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.friendly.url.service.impl.FriendlyURLLocalizationLocalServiceImpl
 * @see com.liferay.friendly.url.service.FriendlyURLLocalizationLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class FriendlyURLLocalizationLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements FriendlyURLLocalizationLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.friendly.url.service.FriendlyURLLocalizationLocalServiceUtil} to access the friendly url localization local service.
	 */

	/**
	 * Adds the friendly url localization to the database. Also notifies the appropriate model listeners.
	 *
	 * @param friendlyURLLocalization the friendly url localization
	 * @return the friendly url localization that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public FriendlyURLLocalization addFriendlyURLLocalization(
		FriendlyURLLocalization friendlyURLLocalization) {
		friendlyURLLocalization.setNew(true);

		return friendlyURLLocalizationPersistence.update(friendlyURLLocalization);
	}

	/**
	 * Creates a new friendly url localization with the primary key. Does not add the friendly url localization to the database.
	 *
	 * @param friendlyURLLocalizationId the primary key for the new friendly url localization
	 * @return the new friendly url localization
	 */
	@Override
	public FriendlyURLLocalization createFriendlyURLLocalization(
		long friendlyURLLocalizationId) {
		return friendlyURLLocalizationPersistence.create(friendlyURLLocalizationId);
	}

	/**
	 * Deletes the friendly url localization with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param friendlyURLLocalizationId the primary key of the friendly url localization
	 * @return the friendly url localization that was removed
	 * @throws PortalException if a friendly url localization with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public FriendlyURLLocalization deleteFriendlyURLLocalization(
		long friendlyURLLocalizationId) throws PortalException {
		return friendlyURLLocalizationPersistence.remove(friendlyURLLocalizationId);
	}

	/**
	 * Deletes the friendly url localization from the database. Also notifies the appropriate model listeners.
	 *
	 * @param friendlyURLLocalization the friendly url localization
	 * @return the friendly url localization that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public FriendlyURLLocalization deleteFriendlyURLLocalization(
		FriendlyURLLocalization friendlyURLLocalization) {
		return friendlyURLLocalizationPersistence.remove(friendlyURLLocalization);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(FriendlyURLLocalization.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return friendlyURLLocalizationPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.friendly.url.model.impl.FriendlyURLLocalizationModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return friendlyURLLocalizationPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.friendly.url.model.impl.FriendlyURLLocalizationModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return friendlyURLLocalizationPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return friendlyURLLocalizationPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return friendlyURLLocalizationPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public FriendlyURLLocalization fetchFriendlyURLLocalization(
		long friendlyURLLocalizationId) {
		return friendlyURLLocalizationPersistence.fetchByPrimaryKey(friendlyURLLocalizationId);
	}

	/**
	 * Returns the friendly url localization with the primary key.
	 *
	 * @param friendlyURLLocalizationId the primary key of the friendly url localization
	 * @return the friendly url localization
	 * @throws PortalException if a friendly url localization with the primary key could not be found
	 */
	@Override
	public FriendlyURLLocalization getFriendlyURLLocalization(
		long friendlyURLLocalizationId) throws PortalException {
		return friendlyURLLocalizationPersistence.findByPrimaryKey(friendlyURLLocalizationId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(friendlyURLLocalizationLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(FriendlyURLLocalization.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"friendlyURLLocalizationId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(friendlyURLLocalizationLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(FriendlyURLLocalization.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"friendlyURLLocalizationId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(friendlyURLLocalizationLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(FriendlyURLLocalization.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"friendlyURLLocalizationId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return friendlyURLLocalizationLocalService.deleteFriendlyURLLocalization((FriendlyURLLocalization)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return friendlyURLLocalizationPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the friendly url localizations.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.friendly.url.model.impl.FriendlyURLLocalizationModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of friendly url localizations
	 * @param end the upper bound of the range of friendly url localizations (not inclusive)
	 * @return the range of friendly url localizations
	 */
	@Override
	public List<FriendlyURLLocalization> getFriendlyURLLocalizations(
		int start, int end) {
		return friendlyURLLocalizationPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of friendly url localizations.
	 *
	 * @return the number of friendly url localizations
	 */
	@Override
	public int getFriendlyURLLocalizationsCount() {
		return friendlyURLLocalizationPersistence.countAll();
	}

	/**
	 * Updates the friendly url localization in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param friendlyURLLocalization the friendly url localization
	 * @return the friendly url localization that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public FriendlyURLLocalization updateFriendlyURLLocalization(
		FriendlyURLLocalization friendlyURLLocalization) {
		return friendlyURLLocalizationPersistence.update(friendlyURLLocalization);
	}

	/**
	 * Returns the friendly url local service.
	 *
	 * @return the friendly url local service
	 */
	public com.liferay.friendly.url.service.FriendlyURLLocalService getFriendlyURLLocalService() {
		return friendlyURLLocalService;
	}

	/**
	 * Sets the friendly url local service.
	 *
	 * @param friendlyURLLocalService the friendly url local service
	 */
	public void setFriendlyURLLocalService(
		com.liferay.friendly.url.service.FriendlyURLLocalService friendlyURLLocalService) {
		this.friendlyURLLocalService = friendlyURLLocalService;
	}

	/**
	 * Returns the friendly url persistence.
	 *
	 * @return the friendly url persistence
	 */
	public FriendlyURLPersistence getFriendlyURLPersistence() {
		return friendlyURLPersistence;
	}

	/**
	 * Sets the friendly url persistence.
	 *
	 * @param friendlyURLPersistence the friendly url persistence
	 */
	public void setFriendlyURLPersistence(
		FriendlyURLPersistence friendlyURLPersistence) {
		this.friendlyURLPersistence = friendlyURLPersistence;
	}

	/**
	 * Returns the friendly url localization local service.
	 *
	 * @return the friendly url localization local service
	 */
	public FriendlyURLLocalizationLocalService getFriendlyURLLocalizationLocalService() {
		return friendlyURLLocalizationLocalService;
	}

	/**
	 * Sets the friendly url localization local service.
	 *
	 * @param friendlyURLLocalizationLocalService the friendly url localization local service
	 */
	public void setFriendlyURLLocalizationLocalService(
		FriendlyURLLocalizationLocalService friendlyURLLocalizationLocalService) {
		this.friendlyURLLocalizationLocalService = friendlyURLLocalizationLocalService;
	}

	/**
	 * Returns the friendly url localization persistence.
	 *
	 * @return the friendly url localization persistence
	 */
	public FriendlyURLLocalizationPersistence getFriendlyURLLocalizationPersistence() {
		return friendlyURLLocalizationPersistence;
	}

	/**
	 * Sets the friendly url localization persistence.
	 *
	 * @param friendlyURLLocalizationPersistence the friendly url localization persistence
	 */
	public void setFriendlyURLLocalizationPersistence(
		FriendlyURLLocalizationPersistence friendlyURLLocalizationPersistence) {
		this.friendlyURLLocalizationPersistence = friendlyURLLocalizationPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("com.liferay.friendly.url.model.FriendlyURLLocalization",
			friendlyURLLocalizationLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.liferay.friendly.url.model.FriendlyURLLocalization");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return FriendlyURLLocalizationLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return FriendlyURLLocalization.class;
	}

	protected String getModelClassName() {
		return FriendlyURLLocalization.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = friendlyURLLocalizationPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.liferay.friendly.url.service.FriendlyURLLocalService.class)
	protected com.liferay.friendly.url.service.FriendlyURLLocalService friendlyURLLocalService;
	@BeanReference(type = FriendlyURLPersistence.class)
	protected FriendlyURLPersistence friendlyURLPersistence;
	@BeanReference(type = FriendlyURLLocalizationLocalService.class)
	protected FriendlyURLLocalizationLocalService friendlyURLLocalizationLocalService;
	@BeanReference(type = FriendlyURLLocalizationPersistence.class)
	protected FriendlyURLLocalizationPersistence friendlyURLLocalizationPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}